Nuand/bladeRF

- host/libraries/libbladeRF/src/xb.c
Lingering cruft from 7e7079de
Fixes CID 1287145
> rm dead code from xb.c

- host/utilities/bladeRF-cli/src/cmd/doc/generate.bash
This might fix the build failures we're seeing on armhf PPA
> generate.bash: gracefully handle pandoc failures

- hdl/fpga/ip/altera/nios_system/simulation/nios_system.vhd
- hdl/fpga/ip/nuand/nuand.do
-Added missing ports to simulation/nios_system.vhd
-Added missing files to nuand.do
-Compile.do will now compile successfully in Modelsim
> hdl: Fixed simulation files

- host/libraries/libbladeRF/src/backend/usb/libusb.c
> Enforce exclusive access to bladeRF when using libusb under Windows

- host/common/include/host_config.h.in
- host/common/include/windows/mkdtemp.h
- host/common/src/windows/mkdtemp.c
- host/libraries/libbladeRF_test/test_config_file/CMakeLists.txt
- host/libraries/libbladeRF_test/test_config_file/src/main.c
This fixes the libbladeRF_test_config_file unit test build under Win32.
> host: libbladeRF_test: win32 fixes for test_config_file

- host/libraries/libbladeRF/src/board/bladerf1/bladerf1.c
If a pre-2.2.0 firmware is flashed to a bladeRF2 device, there is no way
to fix the problem without jumpering into bootloader because the
initialization aborts with a BLADERF_ERR_UNEXPECTED.
Here, we're looking for the bladeRF2 FPGA signatures, and if we find
them, we return from bladerf1_open() early after printing some useful
tips. This allows firmware flashing to occur, but not much else because
the FPGA is not loaded.
Fixes #572
> host: libbladeRF: detect possible bladeRF2 during bladeRF1 init (#572)

- host/libraries/libbladeRF/src/expansion/xb200.c
Verify that dev->xb_data is not NULL before using it.  Also ensure that it is NULL after freeing.
Fixes #575
> host: libbladeRF: check for null xb_data in xb200 fns (#575)

- host/libraries/libbladeRF/src/board/bladerf2/bladerf2.c
Fixes a lockup/crashy bug where bladerf2_get_vctcxo_trim would cause active RX/TX streams to fail.  Also ensures that "set trimdac" won't inadvertently re-enable the trim DAC if it is disabled (e.g. because the PLL is enabled).
>  host: libbladeRF/bladerf2: cache factory trimdac value, preserve trimdac disable state

- host/utilities/bladeRF-cli/src/main.c
If the --load-fpga, --flash-firmware, or --flash-fpga options
are present on the command line, we temporarily set the
BLADERF_FORCE_NO_FPGA_PRESENT environment variable when
opening the device, to trick bladerf_open into not performing
a device initialization before we have the hardware fully
ready to go.
The --load-fpga calls bladerf_load_fpga, which ultimately
calls the correct bladerf*_initialization function to complete
the initialization, so this is fine.
However, the --flash-* options do *not* do this, and therefore,
flashing firmware or FPGA leaves the device in a half-initialized
state (specifically STATE_FIRMWARE_LOADED). If the FPGA is
in the unconfigured state, this is an accurate and consistent,
if useless, state.
But, if the FPGA *has* been configured by a previous …
> bladeRF-cli: ensure device is initialized after deferred open (#612)

- host/libraries/libbladeRF/include/libbladeRF.h
- host/libraries/libbladeRF/src/board/bladerf1/bladerf1.c
- host/libraries/libbladeRF/src/board/bladerf2/bladerf2.c
- host/utilities/bladeRF-cli/src/cmd/printset_hardware.c
- host/utilities/bladeRF-cli/src/cmd/printset_impl.c
> Revert "host: add format macros for bladerf_frequency, bladerf_timestamp"

- host/libraries/libbladeRF/include/libbladeRF.h
- host/libraries/libbladeRF/src/backend/usb/libusb.c
- host/libraries/libbladeRF/src/devinfo.c
- host/utilities/bladeRF-cli/src/cmd/info.c
- host/utilities/bladeRF-cli/src/cmd/probe.c
> Revert "host: add a product description string to devinfo"

- host/libraries/libbladeRF/src/board/bladerf1/bladerf1.c
> bladerf1: don't leave bladerf1_tx_port_map empty

- host/libraries/libbladeRF/src/board/bladerf2/bladerf2.c
Renames a couple static functions to clarify their usage
Changes a couple more uint64_t to bladerf_frequency
Remove `__FUNCTION__` from a few warnings/errors where it is just
clutter
Closes #606
> bladerf2: rename convenience static fns, misc cleanup

- host/libraries/libbladeRF/src/backend/usb/libusb.c
- host/utilities/bladeRF-cli/src/cmd/probe.c
In the Windows world, libusb_open() fails if the device is already open.  This results in a misleading error if a user does, say, `bladeRF-cli -e probe`.
As a workaround, lusb_probe now passes back the data it does have (backend, USB bus, USB address), and sets the serial number to "ANY".  bladeRF-cli's probe command now looks for this and handles it.
Fixes #641
> host: improve handling of LIBUSB_ERROR_ACCESS during probe

- host/utilities/bladeRF-cli/src/cmd/trigger.c
> bladeRF-cli: fix missing return in error case

- host/libraries/libbladeRF/src/backend/dummy/dummy.c
- host/libraries/libbladeRF/src/backend/usb/cyapi.c
> host: libbladeRF: fix wrong get_flash_id fptr in dummy.c

- fpga_common/include/lms.h
- host/common/src/parse.c
- host/libraries/libbladeRF/src/backend/usb/libusb.c
- host/libraries/libbladeRF/src/board/bladerf1/bladerf1.c
- host/libraries/libbladeRF/src/board/bladerf2/bladerf2.c
- host/libraries/libbladeRF_test/test_repeated_stream/src/main.c
- host/utilities/bladeRF-cli/src/cmd/tx.c
Fixed 7 files with clang-scan warnings.
> various clang-scan fixes

- host/libraries/libbladeRF/src/board/bladerf1/bladerf1.c
New messages have a lower severity, explain what will happen
instead (manual gain control), and include an info message with
guidance for solving the issue.
> libbladeRF: bladerf1: improve AGC-unavailable messaging (fixes #686)

- host/libraries/libbladeRF/src/board/bladerf1/bladerf1.c
_apportion_gain did not pay heed to the step size of the gain
range, causing it to end up with invalid values for LNA and
RXVGA2.
We now ensure that the allocation mod <stepsize> is 0, so that
other, more flexible gain stages can be used to pick up the
remainder.
> host: bladerf1: fix apportioning of overall gain

- host/libraries/libbladeRF/src/board/bladerf2/bladerf2.c
If we've already done the FIR filter change for low sample rates,
we don't need to do it again when changing to another low sample
rate.
> host: bladerf2: fix overeager FIR filter setting in set_sample_rate

- host/libraries/libbladeRF_test/test_ctrl/src/main.c
- host/libraries/libbladeRF_test/test_ctrl/src/test_bandwidth.c
- host/libraries/libbladeRF_test/test_ctrl/src/test_correction.c
- host/libraries/libbladeRF_test/test_ctrl/src/test_ctrl.h
- host/libraries/libbladeRF_test/test_ctrl/src/test_enable_module.c
- host/libraries/libbladeRF_test/test_ctrl/src/test_frequency.c
- host/libraries/libbladeRF_test/test_ctrl/src/test_gain.c
- host/libraries/libbladeRF_test/test_ctrl/src/test_loopback.c
- host/libraries/libbladeRF_test/test_ctrl/src/test_lpf_mode.c
- host/libraries/libbladeRF_test/test_ctrl/src/test_rx_mux.c
- host/libraries/libbladeRF_test/test_ctrl/src/test_samplerate.c
- host/libraries/libbladeRF_test/test_ctrl/src/test_sampling.c
- host/libraries/libbladeRF_test/test_ctrl/src/test_threads.c
- host/libraries/libbladeRF_test/test_ctrl/src/test_xb200.c
Most sub-tests of libbladeRF_test_ctrl pass, except for threads (see #705).
> host: test_ctrl: fixup for bladerf2

- host/libraries/libbladeRF_test/test_ctrl/src/test_bandwidth.c
- host/libraries/libbladeRF_test/test_ctrl/src/test_correction.c
- host/libraries/libbladeRF_test/test_ctrl/src/test_ctrl.h
- host/libraries/libbladeRF_test/test_ctrl/src/test_enable_module.c
- host/libraries/libbladeRF_test/test_ctrl/src/test_frequency.c
- host/libraries/libbladeRF_test/test_ctrl/src/test_gain.c
- host/libraries/libbladeRF_test/test_ctrl/src/test_loopback.c
- host/libraries/libbladeRF_test/test_ctrl/src/test_lpf_mode.c
- host/libraries/libbladeRF_test/test_ctrl/src/test_rx_mux.c
- host/libraries/libbladeRF_test/test_ctrl/src/test_samplerate.c
- host/libraries/libbladeRF_test/test_ctrl/src/test_sampling.c
- host/libraries/libbladeRF_test/test_ctrl/src/test_threads.c
- host/libraries/libbladeRF_test/test_ctrl/src/test_xb200.c
- host/libraries/libbladeRF_test/test_repeated_stream/src/main.c
Cleans up build failures introduced by #706
> host: libbladeRF_test: fix build failures on Windows

- host/libraries/libbladeRF/src/board/bladerf2/bladerf2.c
During the recent refactor, the RFIC FIR filter functions got
wrapped in a MUTEX_LOCK.  This is incompatible with their use
by bladerf2_set_sample_rate, which is called within a MUTEX_LOCK.
:woman_facepalming:
> host: bladerf2: fix double-mutexing in low-samplerate-mode

- host/utilities/bladeRF-cli/CMakeLists.txt
- host/utilities/bladeRF-cli/src/cmd/ADDING_COMMANDS.md
- host/utilities/bladeRF-cli/src/cmd/cmd.c
Refactor/simplify the command declarations
Sort the commands
> host: bladeRF-cli: cmd.c: refactor, code formatting/cleanup

- hdl/fpga/ip/analogdevicesinc/no_OS/CMakeLists.txt
- host/libraries/libbladeRF/src/board/bladerf2/rfic_fpga.c
> fix build errors

- host/libraries/libbladeRF_bindings/python/bladerf/_bladerf.py
These two commits fix some pointer errors in the libbladeRF Python bindings to make several of the "query" type functions work correctly.
> Python binding fixes
