debian/changelog
Bring 2015.02 entry back, run through dch to bump timestamp
and clean up formatting.
stray lines wander in
entire revisions gone
there's an app for this
=> fixup debian/changelog

debian/bladerf-firmware-fx3.postinst, debian/bladerf-fpga-hostedx115.postinst, debian/bladerf-fpga-hostedx40.postinst
Update pointers for the auto-downloaders of FPGA and firmware images
=> debian: firmware to v1.8.1, fpga to v0.4.1

host/common/include/host_config.h.in
These functions come with MSVC 2015 (vc14) as part of the c99 support.
The compatibility definitions in host_config.h.in were causing
a compilation error. This fix disables the compatibility definitions
when the more recent vc14 compiler is detected.
=> libbladeRF: use c99 snprintf/vsnprintf for vc14

hdl/quartus/build.tcl
This handles the case where TALKBACK_ENABLED has never been explicitly
set and is empty.
=> hdl: check for null TALKBACK_ENABLED (#354)

debian/bladerf-firmware-fx3.postinst, debian/bladerf-fpga-hostedx115.postinst, debian/bladerf-fpga-hostedx40.postinst
Revises the postinst scripts to be more careful about leaving broken stuff in /usr/share/Nuand/bladeRF.
Also improve commonality between the scripts...
=> debian: gracefully handle failed wget when downloading FPGA/firmware images (#454)

host/common/include/osx/clock_gettime.h, host/common/src/osx/clock_gettime.c
The 2016.06 release (and also current master) does not build on macOS Sierra.  I found this when attempting to install on macOS Sierra via Homebrew.
This change properly builds using the simplest CMake build on macOS Sierra but has not been tested on earlier versions of macOS.
```cmake
$ mkdir build
$ cd build
$ cmake ..
$ make
```
I ran the most basic test of running the `bladerf-cli` program, but did not run any tests against a bladeRF device.  Is there a mechanism for doing this and reporting results?
=> Fix build on macOS Sierra.

debian/bladerf-fpga-hostedx115.postinst, debian/bladerf-fpga-hostedx40.postinst
Failing the postinst breaks the overall install operation and leaves packages half-configured.
=> Don't fail postinst entirely on FPGA download error

hdl/fpga/ip/altera/nios_system/software/bladeRF_nios/src/devices.c
Unnecessary bit is being set when writing address.
=> nios: fix si5338_write typo (#491)

debian/bladerf-firmware-fx3.postinst, debian/bladerf-fpga-hostedx115.postinst, debian/bladerf-fpga-hostedx40.postinst, debian/changelog, host/libraries/libbladeRF/src/file_ops.c
The change from directly overwriting the files in /usr/share/Nuand/bladeRF to creating an intermediate temp file introduced an issue where the binaries are only readable by the root user, because mktemp creates temp files chmod 0600.
This pull request has two fixes:
1) Do a chmod 0444 on these files after moving them into place
2) When file_read_buffer fails, print out a more useful error message to call attention to this issue
=> Fix permissions on downloaded FPGA/firmware images in debian package

host/CMakeLists.txt, host/common/include/host_config.h.in, host/common/include/osx/clock_gettime.h, host/common/src/osx/clock_gettime.c, host/libraries/libbladeRF/CMakeLists.txt
AvailabilityMacros.h is part of Xcode and not the underlying OS and is not a reliable indicator of what the underlying OS version is.  So, building with Xcode 8.x (with support for macOS 10.12, with clock_gettime) on macOS 10.11 (which does not have clock_gettime) fails.
Instead, we can use CMake's `check_library_exists` to directly test for clock_gettime in libc, and then build the shim if required.
=> macOS: detect clock_gettime presence directly, instead of inferring from version (#508)

host/libraries/libbladeRF/src/backend/usb/usb.c
backend_fns_usb_legacy was missing a .set_agc_dc_correction member,
which causes issues with some compilers.  Stubbed in
set_agc_dc_correction_unsupported.
=> host/usb.c: add missing set_agc_dc_correction handler (#512)

host/common/src/dc_calibration.c
MSVC warns of loss of precision on implicit conversion from float to
int16_t.  Instead of relying on truncation, do a proper round with
bounds-checking.
=> host: dc_calibration.c: fix int conversion in rx_cal_dc_off (#515)

host/libraries/libbladeRF/src/backend/usb/cyapi.c
When working on mutexes for the libusb backend, I noticed that I needed
to ReleaseMutex() when closing the device, or else that device would not
be usable again until all of the mutexes were released.
I have not tested this with CyAPI as yet, but I believe the same problem
will occur, and I also believe this may fix it.
Fixes #520
=> host/libbladeRF/cyapi: ReleaseMutex before CloseHandle

host/README.md
On recent versions of Windows / Visual Studio, struct timespec is
already defined, and the definition is subtly different than what
pthreads-win32 is built with.
It may be possible to handle this in a more automatic fashion via CMake,
but this is TBD.
=> host/README.md: add pthreads-win32 build instructions (#447)

host/cmake/modules/Version.cmake
We explicitly set VERSION_INFO_EXTRA to "" for release builds, which
causes (${VERSION_INFO_EXTRA} STREQUAL "") to evaluate to
( STREQUAL ""), a syntax error.
Quoting ${VERSION_INFO_EXTRA} should not cause the ambigious condition
foretold in CMP0054, so doing that.
=> host/cmake: fix regression from #511

fx3_firmware/README.md
The cmake invocation was incorrect and pointed at a non-existant
filename.
Initial report: https://nuand.com/forums/viewtopic.php?f=4&t=3977
=> fx3: fix cmake invocation in README.md

host/libraries/libbladeRF/CMakeLists.txt
Previously, cmake would only rebuild the doxygen output if libbladeRF.h
or the Doxyfile itself changed. Now, it will be rebuilt if any of the
examples, long-form documentations, or images change as well.
=> host: improved dependency checking for doxygen rebuild

host/libraries/libbladeRF/src/config.c
This leads to AGC being disabled on every call of bladeRF-cli.
Please see https://github.com/Nuand/bladeRF/blob/master/host/utilities/bladeRF-cli/src/cmd/xb300.c#L117 for the proper usage.
I'm not sure if only checking LSB is the proper way to do it, as val (uint32_t) is uninitialized and str2bool sees it as bool (on my machine "off" is 2048 and "on" is 2049), but it would even work if those "else if's" are being
reordered, thus initialized by something else to a non-zero value, or you could zero it right before the str2bool call.
The printf call might not be needed anymore.
Notes:
With the latest changes in kalibrate-bladeRF (add win32 support), changing the buffer sizes of m_x_cb, m_y_cb, m_e_cb, the results of the program look even more odd. Were those changes intended? Either the …
=> Fix wrong usage of str2bool

host/libraries/libbladeRF/src/backend/usb/libusb.c
Calling ReleaseMutex without CloseHandle will let the mutex still exist until the process exists.
In such scenario, further calls to CreateMutex will succeed but GetLastError will return 183 (ERROR_ALREADY_EXISTS) causing libbladerf to fail opening the device. This can be assessed by running ```libbladeRF_test_open.exe -c 2 -v debug```.
Cypress backend is not affected as it systematically closes the handle after releasing the mutex.
=> Fix mutex handling for Windows in libusb backend.

host/libraries/libbladeRF_bindings/matlab/libbladeRF_proto.m
Updates the libbladeRF_proto.m file to have library calls added since it was first generated, and rearranges the order to make future edits easier.
Fixes #543
=> host: libbladeRF_bindings: matlab: update libbladeRF_proto.m

host/libraries/libbladeRF_test/test_config_file/src/main.c
On older compilers, 'for' loop initial declarations are not allowed by
default. So, use the old style for maximum compatibility.
h/t Christophe Devine
=> host: test: fix compile errors on test_config_file

host/libraries/libbladeRF/src/device_identifier.c
Instead of using the length of the source string, use
sizeof(d->serial) to limit strncpy to the length of the destination
string.
Fixes #555
=> host: libbladeRF: fix handle_serial strncpy warnings (#555)

host/misc/docker/parallel.bash
Gracefully handle situations where there's no `nproc` command or `/proc/loadavg` file when doing parallel builds.
=> host: docker: fixes for non-linux systems (e.g. MacOS)

host/libraries/libbladeRF/src/backend/usb/libusb.c, host/libraries/libbladeRF/src/driver/thirdparty/adi/ad9361.c
Tested on FreeBSD only but very low risk across the board
=> Fixes so we can build on freebsd again 

host/utilities/bladeRF-cli/src/cmd/printset_impl.c
I was getting familiar with bladeRF-cli and testing my bladeRF2 and was getting errors when trying to set loopback modes:
```
radiodev@f838f94589fe:~$ bladeRF-cli -i
bladeRF> info
Board:                    bladerf2
Serial #:                 8a952f477f514a11a049743f0c98a38b
VCTCXO DAC calibration:   0x1f6b
FPGA size:                49 KLE
FPGA loaded:              yes
USB bus:                  2
USB address:              6
USB speed:                SuperSpeed
Backend:                  libusb
Instance:                 0
bladeRF> print loopback
Loopback mode: none
bladeRF> set loopback
Usage: set loopback <mode>, where <mode> is one of the following:
bb_txlpf_rxvga2   Baseband loopback: TXLPF output --> RXVGA2 input
bb_txlpf_rxlpf    Baseband loopback: TXLPF output --> RXLPF input …
```
=> "set loopback" help dialog aware of board type

host/libraries/libbladeRF/doc/doxygen/mainpage.dox, host/libraries/libbladeRF/doc/doxygen/relnotes_2_0.dox, host/libraries/libbladeRF/doc/doxygen/relnotes_2_0_0.dox, host/libraries/libbladeRF/include/libbladeRF.h
Updates the release notes for v2.0 to include more useful information, less useless information, and fewer typos.  More consistent and readable, hopefully.
Also fixes one error in the documentation in libbladeRF.h.
=> libbladeRF: polished release notes for v2.0

host/utilities/bladeRF-cli/src/cmd/printset_hardware.c
Fixes a minor inconvenience caused by probing the PLL lock status too
quickly after enabling the PLL for the first time: the PLL will report
unlocked even though a valid reference is present.
Addresses issue #584.
=> host: bladeRF-cli: Add 200 ms delay before probing PLL lock status

host/common/include/windows/nanosleep.h, host/common/src/windows/nanosleep.c, host/utilities/bladeRF-cli/CMakeLists.txt, host/utilities/bladeRF-cli/src/cmd/printset_hardware.c
Windows does not have nanosleep(), so this PR emulates it with a wrapper that calls Sleep().
=> host: add nanosleep shim for Windows

host/libraries/libbladeRF/include/bladeRF2.h, host/libraries/libbladeRF/src/board/bladerf2/bladerf2.c, host/libraries/libbladeRF/src/board/bladerf2/params.c, host/utilities/bladeRF-cli/src/cmd/printset_hardware.c
To support sample rates below ~2.1 Msps, interpolation/decimation must be enabled on the RFIC's FIR filter.  We do this by checking to see if we can achieve the current sample rate with the currently-enabled filter, and if not, we enable a 4x filter.
This PR adds:
- LPF taps for the RX and TX FIR filters
- API functions to get/set the filters
- enums for the available filters
- an entry in the RFIC status print from bladeRF-cli
Fixes #581
=> bladerf2: Support sample rates down to 0.521 Msps (#581)

host/cmake/modules/FindLibEdit.cmake, host/common/src/parse.c, host/utilities/bladeRF-cli/CMakeLists.txt, host/utilities/bladeRF-cli/src/input/editline.c
* Add libedit support to the bladeRF-cli utility
* Add a libedit input backend
* Allow the build system to be configured to link to libedit
* Add FindLibEdit cmake module
* Update bladeRF-cli build to use libedit if ENABLE_LIBEDIT is set or
libedit is found and libtecla is not
* Fix memory leak when a unterminated quoted string is given in
interactive mode
Fixes: #319
=> bladeRF-cli: Add libedit support

debian/control, debian/libbladerf-doc.docs, debian/libbladerf-doc.install, debian/rules, host/libraries/libbladeRF/CMakeLists.txt
Instead of leaving the deftly-assembled API documentation in the build/ dir, with the vast storehouse of knowledge and useful information treated as mere ephemera, this PR installs them with the rest of libbladeRF.
Also adds a debian package: libbladerf-doc
=> libbladeRF: install doxygen docs

host/libraries/libbladeRF/src/board/bladerf1/bladerf1.c, host/libraries/libbladeRF/src/board/bladerf2/bladerf2.c
On the bladeRF 1, remove the redundant "automatic" setting
and rename "default" to "automatic". Also directly use
enum values instead of the reverse-compat #defines.
On the bladeRF 2, rename "default" to "automatic".
Intent: make it more clear whether the gain mode is automatic
or manual, without having to "know" that the default is automatic.
Fixes #601
=> libbladeRF: adjust list of RX gain modes (#601)

hdl/CHANGELOG, hdl/fpga/platforms/bladerf-micro/software/bladeRF_nios/src/fpga_version.h, hdl/fpga/platforms/bladerf/software/bladeRF_nios/src/fpga_version.h, hdl/fpga/platforms/bladerf/vhdl/bladerf-hosted.vhd, hdl/fpga/platforms/bladerf/vhdl/bladerf_p.vhd, host/libraries/libbladeRF/include/bladeRF1.h, host/libraries/libbladeRF/src/board/bladerf1/bladerf1.c, host/libraries/libbladeRF/src/board/bladerf1/compatibility.c, host/libraries/libbladeRF/src/board/bladerf2/compatibility.c
Fixes #607
The nios_gpio bit assignment for AGC_EN was already being used for
led(1). This commit also fixes a bug in the agc_band_sel signal
assignment introduced in 3b670ca.
=> bladeRF1: Fix nios_gpio assignment for AGC_EN

host/libraries/libbladeRF/include/libbladeRF.h, host/libraries/libbladeRF/src/board/bladerf1/bladerf1.c, host/utilities/bladeRF-cli/src/cmd/printset.c, host/utilities/bladeRF-cli/src/cmd/printset_hardware.c
Implements the RF port getters/setters for the bladeRF 1, moves these functions into the low-level functions section of libbladeRF.h, and implements reading of these settings in bladeRF-cli's 'print hardware' command.
Fixes #600
=> bladerf1: implement bladerf_{get,set}_rf_port[s]

host/libraries/libbladeRF/include/libbladeRF.h, host/libraries/libbladeRF/src/board/bladerf1/bladerf1.c, host/libraries/libbladeRF/src/board/bladerf2/bladerf2.c, host/utilities/bladeRF-cli/src/cmd/printset_hardware.c, host/utilities/bladeRF-cli/src/cmd/printset_impl.c
Adds new format macros for displaying bladerf_frequency and bladerf_timestamp values to libbladeRF.h.
Updates bladerf1.c, bladerf2.c, and bladeRF-cli's print/set to use the new format macros, and also to use the proper typedefs.
Fixes #577
=> host: add format macros for bladerf_frequency, bladerf_timestamp

host/libraries/libbladeRF/include/libbladeRF.h, host/libraries/libbladeRF/src/backend/usb/libusb.c, host/libraries/libbladeRF/src/devinfo.c, host/utilities/bladeRF-cli/src/cmd/info.c, host/utilities/bladeRF-cli/src/cmd/probe.c
Displays a description for each device found during a bladeRF-cli --probe:
```
Description:    Nuand bladeRF 2.0
Backend:        libusb
Serial:         <redacted>
USB Bus:        4
USB Address:    36
```
This is built from the USB device descriptor, piggy-backing on the same functionality that populates the serial number.
Currently libusb-only; on cyusb, it will likely display "<unknown>".
=> host: add a product description string to devinfo

host/libraries/libbladeRF/include/bladeRF2.h, host/libraries/libbladeRF/include/libbladeRF.h, host/libraries/libbladeRF/src/board/bladerf1/bladerf1.c, host/libraries/libbladeRF/src/board/bladerf2/bladerf2.c
Adds new format macros for displaying bladerf_frequency and
bladerf_timestamp values to libbladeRF.h.
Transitions bladerf1.c and bladerf2.c to use these new macros,
and also cleans up a few more places where the typedefs aren't
currently used.
Also fixes a doxygen warning for undocumented #defines in
bladeRF2.h.
Fixes #577
Fixes #618
Fixes #620
=> libbladeRF: add format macros for frequency, timestamp

host/libraries/libbladeRF/include/libbladeRF.h, host/libraries/libbladeRF/src/backend/usb/libusb.c, host/libraries/libbladeRF/src/devinfo.c, host/utilities/bladeRF-cli/src/cmd/info.c, host/utilities/bladeRF-cli/src/cmd/probe.c
Adds 'manufacturer' and 'product' members to the bladerf_devinfo struct, and ensures they are properly initialized and populated during enumeration.
These contain the human-readable manufacturer and product names from the USB device descriptor, and are displayed by bladeRF-cli during 'probe' and 'info' commands.
Note: This is a reimplementation of PR #611, which tried to be a little too clever.
Fixes #611 
Fixes #615 
Fixes #616 
Fixes #617
=> host: Add manufacturer/product strings to device information

host/libraries/libbladeRF/src/board/bladerf2/bladerf2.c
on the bladerf2, bladerf_trigger_arm was calling fpga_trigger_fire
instead of fpga_trigger_arm, creating a situation where the triggers
were not being armed.
Fixes #632
=> libbladeRF: fix bladerf2_trigger_arm typo

host/libraries/libbladeRF/include/libbladeRF.h, host/libraries/libbladeRF/src/bladerf.c
Adds a bladerf_get_serial_struct function, which is similar
in functionality to bladerf_get_serial, but instead of requiring
a user-supplied buffer of at least BLADERF_SERIAL_LENGTH bytes,
it expects a pointer to a struct bladerf_serial which itself has
a buffer of BLADERF_SERIAL_LENGTH bytes as a member.
This turns BLADERF_SERIAL_LENGTH into an API-internal value,
instead of something that API users have to be intently aware of.
Fixes #382
=> libbladeRF: add bladerf_get_serial_struct function

firmware_common/bladeRF.h, fx3_firmware/CMakeLists.txt, fx3_firmware/src/bladeRF.c, fx3_firmware/src/flash.c, fx3_firmware/src/flash.h, host/libraries/libbladeRF/include/libbladeRF.h, host/libraries/libbladeRF/src/backend/backend.h, host/libraries/libbladeRF/src/backend/dummy/dummy.c, host/libraries/libbladeRF/src/backend/usb/usb.c, host/libraries/libbladeRF/src/backend/usb/usb.h, host/libraries/libbladeRF/src/bladerf.c, host/libraries/libbladeRF/src/board/bladerf1/bladerf1.c, host/libraries/libbladeRF/src/board/bladerf1/capabilities.c, host/libraries/libbladeRF/src/board/bladerf1/compatibility.c, host/libraries/libbladeRF/src/board/bladerf1/flash.c, host/libraries/libbladeRF/src/board/bladerf1/flash.h, host/libraries/libbladeRF/src/board/bladerf2/bladerf2.c, host/libraries/libbladeRF/src/board/bladerf2/capabilities.c, host/libraries/libbladeRF/src/board/bladerf2/compatibility.c, host/libraries/libbladeRF/src/board/board.h, host/libraries/libbladeRF_bindings/python/bladerf/_bladerf.py, host/libraries/libbladeRF_bindings/python/bladerf/_cdef.py, host/libraries/libbladeRF_bindings/python/bladerf/_tool.py, host/libraries/libbladeRF_bindings/python/setup.py, host/utilities/bladeRF-cli/src/cmd/info.c
First "half" of fixing issue #571. Provides a mechanism to read out the manufacturer and device IDs from the SPI flash. This can be used to determine the density and architecture.
=> Probe flash ID and return its size

host/libraries/libbladeRF/src/backend/usb/cyapi.c, host/libraries/libbladeRF/src/backend/usb/libusb.c
MSVC is a stickler about how structs are populated, and
so we need to put something in libusb.c and cyapi.c even
though get_flash_id is actually handled in usb.c
=> libbladeRF: add get_flash_id to usb_fns struct in usb drivers

host/libraries/libbladeRF/src/bladerf.c
Fixes stringop-truncation warning in newer gcc versions
=> bladerf: fix strncpy in bladerf_get_serial_struct

host/common/src/parse.c
parse.c is releasing memory for strings, after it assigns the memory location to a struct. This results in the memory potentially being overwritten by subsequent allocations before it's referenced. 
Fixes #643
=> Memory deallocation fix

host/libraries/libbladeRF/CMakeLists.txt, host/libraries/libbladeRF/src/backend/usb/nios_access.c
There are a few functions which are used very often, resulting in
a lot of unnecessary bloat on the verbose logging.
Unless ENABLE_LIBBLADERF_NIOS_ACCESS_LOG_VERBOSE is defined, the
following functions will no longer print verbose logging output:
nios_si5338_read
nios_si5338_write
nios_lms6_read
nios_lms6_write
nios_ad9361_spi_read
nios_ad9361_spi_write
nios_adi_axi_read
nios_adi_axi_write
nios_rffe_control_read
nios_rffe_control_write
=> host: nios_access: reduce verbose logging spew

hdl/fpga/ip/nuand/synthesis/lms6002d/vhdl/bladerf_agc_lms_drv.vhd, hdl/fpga/platforms/bladerf/constraints/bladerf.sdc, hdl/fpga/platforms/bladerf/vhdl/bladerf-hosted.vhd
This ensures that the SPI controllers have a consistent clock to work with, instead of rx_clock (which depends on the configured ADC sample rate). This ensures the SPI clock will always be 20 MHz, and that everything is passing between known clock domains.
Also registers the gain change request lines going into bladerf_agc_lms_drv to improve timing margin, and adds a set_output_delay timing constraint on lms_sclk.
Fixes #640
=> hdl: bladerf1: move AGC SPI driver into 80 MHz clock domain

hdl/fpga/ip/nuand/command_uart/vhdl/command_uart.vhd, hdl/fpga/platforms/bladerf/constraints/bladerf.sdc, hdl/fpga/platforms/bladerf/vhdl/bladerf-hosted.vhd
Improves timing closure probability of bladerf1 hosted builds by adding registers and synchronizers.
This affects the following components:
- command_uart: rs232_sout is now registered
- tx_*_fifo: fixed the set_false_paths in the SDC
- rx mux: lms_rx_enable_qualified is now synchronized into the rx_clock domain
- discretes: fx3_ctl and fx3_uart_cts are now registered into the fx3_pclk_pll domain; xb_gpio_dir and dac_csx are registered in the 80MHz domain
With this and #642, we are reliably passing timing.  (Hooray!)
Fixes #395
=> hdl: bladerf1: timing improvements

host/libraries/libbladeRF/src/board/bladerf1/bladerf1.c
On the bladerf2, we have a comparatively long initialization process,
and thus we skip the init if we're "just" loading an FPGA, e.g. with
the -l option to bladeRF-cli.
This adds the same bypass to bladerf1.
=> host: bladerf1: skip init if BLADERF_FORCE_NO_FPGA_PRESENT

hdl/quartus/build_bladerf.sh
The use of `readlink` with `quartus_sh` results in bogus paths when
inside a Cygwin environment. Use of `readlink` was determined to be
unnecessary and was removed.
=> hdl: build: Cygwin compatibility

host/libraries/libbladeRF_bindings/matlab/bladeRF_Simulink.m
processTunedPropertiesImpl() was not updated during the migration
from tx_vga1+tx_vga2 to tx_gain.
h/t mando238
Fixes #654
=> host: matlab: fix tx_gain property handling in simulink

host/libraries/libbladeRF/src/board/bladerf2/bladerf2.c
These were somehow not implemented, but were pretty easy copies from bladerf1.c
=> host: libbladerf/bladerf2: implement bladerf_{set,get}_stream_timeout

fx3_firmware/src/bladeRF.c
When libbladeRF is built with ENABLE_USB_DEV_RESET_ON_OPEN, a
USB port reset is performed on open, to work around some xHCI
controller bugs.
This hits the CyFxbladeRFApplnUSBEventCB() callback with an
event type of CY_U3P_USB_EVENT_RESET, which is then dispatched
to StopApplication(), which calls NuandRFLink.stop() or
NuandFpgaConfig.stop() or does nothing, depending on what the
glAppMode is.
Unfortunately, if the FX3 is loading an FPGA bitstream from the
SPI flash to the FPGA, NuandFpgaConfig.stop() also stops that
dead, and bladeRFAppThread_Entry() progresses forward and we end
up with an unconfigured FPGA. In that case, libbladeRF will then
go through the FPGA autoloading process.
This is essentially a race condition: which FPGA image is loaded,
if any, depends on the time between …
=> fx3: don't stop flash->fpga autoload on USB reset

firmware_common/bladeRF.h, fx3_firmware/CMakeLists.txt, fx3_firmware/src/bladeRF.c, fx3_firmware/src/fpga.c, fx3_firmware/src/fpga.h, host/libraries/libbladeRF/include/libbladeRF.h, host/libraries/libbladeRF/src/backend/backend.h, host/libraries/libbladeRF/src/backend/usb/usb.c, host/libraries/libbladeRF/src/bladerf.c, host/libraries/libbladeRF/src/board/bladerf1/bladerf1.c, host/libraries/libbladeRF/src/board/bladerf1/capabilities.c, host/libraries/libbladeRF/src/board/bladerf1/compatibility.c, host/libraries/libbladeRF/src/board/bladerf2/bladerf2.c, host/libraries/libbladeRF/src/board/bladerf2/capabilities.c, host/libraries/libbladeRF/src/board/bladerf2/compatibility.c, host/libraries/libbladeRF/src/board/board.h, host/utilities/bladeRF-cli/src/cmd/version.c
In a case where multiple FPGA images may be in play (e.g. host autoloading vs SPI flash autoloading), it is desirable to have more information about the source of the currently-active FPGA bitstream.
This PR adds the following features:
- fx3_firmware v2.3.1
- when an FPGA bitstream is loaded, set a global indicating whether it was programmed by SPI flash or USB host
- adds a BLADE_USB_CMD_QUERY_FPGA_SOURCE command
- libbladeRF
- add bladerf_get_fpga_source() API function
- add bladerf_fpga_source enum
- add capability BLADERF_CAP_FW_FPGA_SOURCE, which is active when firmware version >= 2.3.1
- bladeRF-cli
- identify the source of the currently-running FPGA image, if known, in response to the 'version' command
Fixes #646
=> Identify the last source (SPI or USB) which programmed the FPGA

host/libraries/libbladeRF/src/streaming/async.c, host/libraries/libbladeRF/src/streaming/async.h, host/libraries/libbladeRF/src/streaming/sync_worker.c
In a case where we have a long stream timeout, e.g. when using
triggered receive, the long stream timeout is being rendered
ineffective by the per-transfer timeout, which defaults to
1000 ms.
This adds two functions to async, for setting and getting the
transfer timeout:
```
int async_set_transfer_timeout(struct bladerf_stream *stream,
unsigned int transfer_timeout_ms);
int async_get_transfer_timeout(struct bladerf_stream *stream,
unsigned int *transfer_timeout_ms);
```
This also calls `async_set_transfer_timeout` in `sync_worker_init`,
setting it to either the `BULK_TIMEOUT_MS` from usb.h (1000 ms)
or the `timeout_ms` for the stream (user-specified), whichever is
longer.
Fixes #655
=> host: libbladeRF/sync: extend transfer timeout to match stream timeout

host/libraries/libbladeRF_bindings/python/scripts/import_header.py
fixes:
- Script will now look in the same dir as the input file
(e.g. ../../../libbladeRF/include/) for other headers. This
is specifically to let it find bladeRF1.h and bladeRF2.h
more expeditiously.
- Create a stoplist of lines to not include in the output.
This largely consists of typedefs from pycparser's fake
system header files.
=> host: python: improve import_header.py script

host/common/include/windows/nanosleep.h, host/common/src/windows/nanosleep.c
default header sort on nanosleep.c puts nanosleep.h above pthread.h, which creates an implicit definition of struct timespec.
Fixes #669
=> host: common: include pthread.h in nanosleep.h (#669)

host/utilities/bladeRF-cli/src/cmd/printset_impl.c
When printing bandwidth, frequency, and sample rate, display the
supported ranges in parantheses after the current value.
=> host: bladeRF-cli: print ranges on sample rate, bandwidth, frequency

hdl/fpga/platforms/bladerf-micro/constraints/pins.tcl
Add a weak pull-up on fx3_uart_rxd
This is a bus used for both FPGA-to-FX3 UART data and FX3-to-Flash
SPI data, and without something driving it, it tends to float around
0.55 volts (which is very much a low/asserted signal for the UART).
When the FX3 SPI interface has the bus, it puts the FPGA into reset
via fx3_ctl(7), and fx3_uart_rxd goes high-Z accordingly.
I suspect what we're running into is a race condition between the FX3
reconfiguring the pin to UART mode and bringing the FPGA out of reset,
and the FPGA shifting from high-Z to high/idle, given:
- All of the "junk bytes" seen so far have been all ones followed by
all zeroes, e.g. 0xF0, 0xFC, etc
- Being low for 5 clocks and then going high is indistinguishable from
a start bit followed by 0xF0 followed by a stop bit.
Thus, by …
=> hdl: bladerf-micro: weak pull-up on fx3_uart_rxd (#679)

host/libraries/libbladeRF/src/board/bladerf1/bladerf1.c, host/libraries/libbladeRF/src/board/bladerf2/bladerf2.c
In the event dev->backend->load_fpga fails, we need to unlock
the mutex or else we're gonna have a bad time tearing everything
down.
=> libbladeRF: bladerf_load_fpga: release mutex on error (fixes #680)

host/libraries/libbladeRF/doc/doxygen/configfile.dox, host/libraries/libbladeRF/src/helpers/configfile.c
Adds configuration file options for controlling the bias tee supplies.
This PR replaces and closes #650, originally by @mdtopham
=> libbladeRF: add biastee_rx, biastee_tx config file options

host/libraries/libbladeRF_test/test_ctrl/src/test_frequency.c
Fixes the following error:
`error: this decimal constant is unsigned only in ISO C90 [-Werror]`
which was introduced by Nuand/bladeRF#706
=> host: libbladeRF_test: fix decimal const warning on i386

hdl/fpga/platforms/bladerf-micro/build/platform.conf, hdl/fpga/platforms/bladerf/build/platform.conf, hdl/fpga/platforms/common/bladerf/build/common_system.tcl, hdl/quartus/build_bladerf.sh
On xA4/xA9, we can have a larger memory footprint, and we need it for additional features.
=> hdl: nios: parameterize nios2 RAM size by platform/size

host/libraries/libbladeRF/include/bladeRF1.h, host/libraries/libbladeRF/include/libbladeRF.h, host/libraries/libbladeRF/src/bladerf.c, host/libraries/libbladeRF/src/board/bladerf1/bladerf1.c, host/libraries/libbladeRF/src/board/bladerf1/flash.c, host/libraries/libbladeRF/src/board/bladerf2/bladerf2.c, host/libraries/libbladeRF/src/board/bladerf2/common.c, host/libraries/libbladeRF/src/board/bladerf2/common.h, host/libraries/libbladeRF/src/board/board.h, host/utilities/bladeRF-cli/src/cmd/flash_backup.c, host/utilities/bladeRF-cli/src/cmd/flash_image.c, host/utilities/bladeRF-cli/src/cmd/flash_restore.c
Write page counts were updated for 128 Mbit flash chips, but erase block counts were not.  This resulted in FPGA bitstream verification failing on bladeRF 2.0 micro xA9 boards, as flash writes can only turn 1s into 0s, but can't turn 0s into 1s.
Implement a bladerf_get_fpga_bytes() library call to return the expected FPGA image size.
Use the actual bitstream length to compute the number of blocks to erase.
Update bladeRF-cli flash-related functionality.
=> host: fix FPGA flash region erase block count on xA9

hdl/fpga/platforms/common/bladerf/software/bladeRF_nios/src/devices.h, hdl/fpga/platforms/common/bladerf/software/bladeRF_nios/src/devices_rfic.c, hdl/fpga/platforms/common/bladerf/software/bladeRF_nios/src/devices_rfic.h
These are intended for use within headless applications, where queuing is unnecessary, and where the command/channel aren't simply packed into the address.
=> hdl: nios: devices_rfic: add rfic_command_{write,read}_immed() commands

hdl/fpga/platforms/common/bladerf/software/bladeRF_nios/src/devices_rfic_cmds.c
This shift was excised in 9f235dd but it came back during the refactoring in 9601bcc.
h/t @skyhighwings
=> hdl: nios: d_r_cmds: remove unnecessary shift again

hdl/fpga/platforms/common/bladerf/software/bladeRF_nios/src/devices_rfic.c
Fix missing stringification in a couple of debug messages.
=> hdl: nios: fix debugging output in devices_rfic

host/libraries/libbladeRF/doc/doxygen/configfile.dox, host/libraries/libbladeRF/src/helpers/configfile.c
This PR adds the `clock_ref`, `refin_freq`, `clock_sel` and `clock_out` keywords to the config file to control a BladeRF 2.0's clocking.
It also includes PR #821 which fixes a minor typo.
I also tried to extend the `vctcxo_tamer` keyword to make it work both for BladeRF and BladeRF 2.0, it worked fine for 'disabled' and '10MHz' settings, but the '1 PPS' couldn't be implemented as not within the 5MHz-300MHz ref clock range supported by the 2.0. So it is not part of this PR.
=> [ConfigFile] Extend keywords to BladeRF2.0 clocking

host/libraries/libbladeRF/src/helpers/configfile.c
Minor fix parsing the vctcxo_tamer key from the config file.
Unfortunately this key is not supported by BladeRF 2.0 but at least it will make it usable for the original BladeRF.
=> [ConfigFile] Fix parsing of vctcxo_tamer key

CMakeLists.txt
Adding a [cmake project line](https://cmake.org/cmake/help/latest/command/project.html) to CMakeLists.txt gets rid of following error:
I set the name to bladeRF which of course is easily changeable if requested
Cheers!
```
CMake Warning (dev) in CMakeLists.txt:
No project() command is present.  The top-level CMakeLists.txt file must
contain a literal, direct call to the project() command.  Add a line of
code such as
project(ProjectName)
near the top of the file, but after cmake_minimum_required().
CMake is pretending there is a "project(Project)" command on the first
line.
This warning is for project developers.  Use -Wno-dev to suppress it.
```
=> added project() line to CMakeLists.txt to get rid of cmake warning

host/libraries/libbladeRF/src/board/bladerf1/flash.c
This fix enables flashing of the FPGA image into the nonvolatile storage of the bladeRF 2.0 micro xA5:
- enable detection of WINBOND W25Q64JV chip
- add debug output to enable chip ID output for debugging future misdetection issues
=> Add support for xA5 W25Q64JV flash chip

.gitignore, host/libraries/libbladeRF_bindings/matlab/libbladeRF_proto.m
Change architecture string for MacOS on Intel CPUs to 'maci64'.  Resolves #845.
=> Fix incorrect MATLAB architecture string for MacOS 

host/libraries/libbladeRF_test/test_repeater/src/repeater.c
Code copies data from pointer location instead from pointer target - resulting in invalid copied data and overreading from the pointer pointr position.
=> Fix broken memcpy

host/libraries/libbladeRF/src/board/bladerf2/bladerf2.c
Running test_digital_loopback on bladeRF A4, the TX/RX threads cause timeout in nios_access.c with 'Failed to receive NIOS II response'.
Using libusb backend in docker Ubuntu 22.04 container. bladeRF A4 firmware v0.14.0, bladeRF latest or post release v2021.2. 
To reproduce the timeout issue:
- Run `test_digital_loopback` on bladeRF A4 using firmware "2021-10-04 - v0.14.0", multiple times.
After adding the mutex guards, timeouts did not occur. Looking at bladerf1, it is similar but I did not have the hardware to run tests to confirm if the issue is/was present and if the fix applied here would work.
Some bladeRF issues I came across while looking for a fix that appeared related:
- https://github.com/Nuand/bladeRF/issues/813
- https://github.com/Nuand/bladeRF/issues/849
- …
=> libbladeRF: Use mutex around stream config/deconfig

host/libraries/libbladeRF/CMakeLists.txt
While *.h works for make, it fails when using ninja.  This fixes the bug using cmake's file(GLOB) as suggested by DarthGandalf in gentoo-dev-help on irc
https://bugs.gentoo.org/800791
=> use file(GLOB) instead of just globbing

host/libraries/libbladeRF/src/backend/usb/libusb.c
The async API has two codepaths for reporting samples to a user-provided callback depending on whether packet metadata is requested. In the path where it is requested, the code correctly uses bytes_to_samples() to report num_samples. In the path where no metadata is requested, the code uses the previously hardcoded call to bytes_to_sc16q11(), which underreports num_samples by half for SC8_Q7 format samples. This appears to have been an oversight, and this patch corrects the non-metadata path to match the metadata path.
=> libbladerf: correctly report num_samples for SC8_Q7 in async api

host/libraries/libbladeRF/CMakeLists.txt
In `host/libraries/libbladerf/CMakeLists.txt` there was typo in the diagnostic instructing a user to install "libusb" and instead said "lisusb"
=> typo: libbladerf/CMakeLists.txt typo in libusb

host/libraries/libbladeRF/src/helpers/version.c
Specifically, when there's a missing compat table entry. All callers specify that they want to be forgiving of version mismatches, so this seems in the spirit of the call tree.
Ran into this error when playing with a custom-loaded FPGA; if I had flashed the FPGA instead of simply loading it, this could have bricked the blade (or at least forced me into a very involved recovery process).
=> libbladeRF: Return error code instead of asserting in version_check
